### ISSUE TITLE
Error destroying window

### ISSUE THREAD

**Issue by adlgrbz** [adlgrbz/Tkpick#1]
The `Shift+Q` shortcut works with this function.
```
    def quit(self):
        self.destroy()
```

Error:
```python
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/xorg.py", line 458, in _handler
    self._handle(self._display_stop, event)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/mouse/_xorg.py", line 149, in _handle
    self.on_move(px, py)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 78, in inner
    if f(*args) is False:
  File "/home/adil/.local/lib/python3.7/site-packages/Tkpick/workbench.py", line 44, in on_move
    self.geometry(f"{self.ww}x{self.wh}+{x+self.wx}+{y+self.wy}")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1841, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
RuntimeError: main thread is not in main loop
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adil/.local/lib/python3.7/site-packages/Tkpick/workbench.py", line 51, in listener_mouse
    l.join()
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/xorg.py", line 458, in _handler
    self._handle(self._display_stop, event)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/mouse/_xorg.py", line 149, in _handle
    self.on_move(px, py)
  File "/home/adil/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 78, in inner
    if f(*args) is False:
  File "/home/adil/.local/lib/python3.7/site-packages/Tkpick/workbench.py", line 44, in on_move
    self.geometry(f"{self.ww}x{self.wh}+{x+self.wx}+{y+self.wy}")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1841, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
RuntimeError: main thread is not in main loop
```

**Comment by EkremDincel** [comment]
This would fix the problem:
````python
    def quit(self):
        self.after(0, self.destroy)
````
